package = "lest"
version = "0.1.0"
lua = "==5.1"

[description]
summary = ""
maintainer = "Ricardo Casía"
labels = [""]

[source]
url = "https://github.com/rcasia/lest"

[dependencies]
argparse = "0.7.1-1"
nlua = "0.3.2-1"

[dependencies.mini-test]
version = "5bd3b1712183870437e749bca7f35e6ad60d58ab"
git = "github:echasnovski/mini.test"

[run]
command = "nlua"
args = ["src/main.lua"]

[test]
type = "busted"

[build]
type = "builtin"
