package = "lest"
version = "0.1.0"
lua = "==5.1"

[description]
summary = ""
maintainer = "Ricardo Casía"
labels = [""]

[source]
url = "https://github.com/rcasia/lest"
tag = "v0.1.0"

[dependencies]
"mini.test" = "0.16.0"
nlua = "0.3.2-1"
argparse = "0.7.1-1"

[run]
command = "nlua"
args = ["src/main.lua"]

[test]
type = "busted"

[build]
type = "builtin"
[build.install.bin]
lest = "src/main.lua"
