package = "luxuriest.nvim"
version = "0.1.0"
lua = "==5.1"

[description]
summary = ""
maintainer = "Ricardo Casía"
labels = [""]


[dependencies]
argparse = "0.7.1-1"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = ["src/main.lua"]

[test]
type = "busted"

[build]
type = "builtin"
